

-- MySQL Script generated by MySQL Workbench
-- 03/23/17 07:21:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `zes_sviss`;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comment` (
  `CommentId` INT AUTO_INCREMENT,
  `Comment` VARCHAR(100) NOT NULL,
  `CommentTo` VARCHAR(80) NOT NULL,
  `Author` INT UNSIGNED NOT NULL,
  `lastchanged` TIMESTAMP NOT NULL,
  PRIMARY KEY (`CommentId`),
  INDEX `CommentAuthor_idx` (`Author` ASC),
  CONSTRAINT `CommentAuthor`
    FOREIGN KEY (`Author`)
    REFERENCES `User` (`UserNr`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Duty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Duty` (
  `DutyId` INT AUTO_INCREMENT,
  `userid` INT UNSIGNED NOT NULL,
  `starttime` DATETIME NOT NULL,
  `endtime` DATETIME NOT NULL,
  PRIMARY KEY (`DutyId`),
  INDEX `UserDuty_idx` (`userid` ASC),
  CONSTRAINT `UserDuty`
    FOREIGN KEY (`userid`)
    REFERENCES `User` (`UserNr`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Hostgroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hostgroup` (
  `HostgroupId` INT AUTO_INCREMENT,
  `HostgroupName` VARCHAR(45) NOT NULL,
  `AssignedHosts` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`HostgroupId`),
  UNIQUE INDEX `HostgroupName_UNIQUE` (`HostgroupName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Log` (
  `LogId` INT AUTO_INCREMENT,
  `Timestamp` TIMESTAMP NOT NULL,
  `LogCause` VARCHAR(80) NOT NULL,
  `LogEntry` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`LogId`))
ENGINE = InnoDB;

