-- MySQL Script generated by MySQL Workbench
-- 04/03/17 20:49:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zes_sviss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zes_sviss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zes_sviss` DEFAULT CHARACTER SET utf8 ;
USE `zes_sviss` ;

-- -----------------------------------------------------
-- Table `zes_sviss`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zes_sviss`.`User` ;

CREATE TABLE IF NOT EXISTS `zes_sviss`.`User` (
  `UserNr` INT UNSIGNED AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(128) NOT NULL,
  `PersName` VARCHAR(45) NOT NULL,
  `EMail` VARCHAR(50) NOT NULL,
  `AccountType` VARCHAR(15) NOT NULL,
  `Disabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`UserNr`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `EMail_UNIQUE` (`EMail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zes_sviss`.`Comment` ;

CREATE TABLE IF NOT EXISTS `zes_sviss`.`Comment` (
  `CommentId` INT NOT NULL AUTO_INCREMENT,
  `Comment` VARCHAR(100) NOT NULL,
  `CommentTo` VARCHAR(80) NOT NULL,
  `Author` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CommentId`),
  INDEX `CommentAuthor_idx` (`Author` ASC),
  CONSTRAINT `CommentAuthor`
    FOREIGN KEY (`Author`)
    REFERENCES `zes_sviss`.`User` (`UserNr`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Duty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zes_sviss`.`Duty` ;

CREATE TABLE IF NOT EXISTS `zes_sviss`.`Duty` (
  `DutyId` INT AUTO_INCREMENT,
  `DutyAssigne` INT UNSIGNED NOT NULL,
  `DutyStart` DATETIME NOT NULL,
  `DutyEnd` DATETIME NOT NULL,
  PRIMARY KEY (`DutyId`),
  INDEX `UserDuty_idx` (`DutyAssigne` ASC),
  CONSTRAINT `UserDuty`
    FOREIGN KEY (`DutyAssigne`)
    REFERENCES `zes_sviss`.`User` (`UserNr`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Hostgroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zes_sviss`.`Hostgroup` ;

CREATE TABLE IF NOT EXISTS `zes_sviss`.`Hostgroup` (
  `HostgroupId` INT NOT NULL AUTO_INCREMENT,
  `HostgroupName` VARCHAR(45) NOT NULL,
  `AssignedHosts` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`HostgroupId`),
  UNIQUE INDEX `HostgroupName_UNIQUE` (`HostgroupName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zes_sviss`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zes_sviss`.`Log` ;

CREATE TABLE IF NOT EXISTS `zes_sviss`.`Log` (
  `LogId` INT NOT NULL AUTO_INCREMENT,
  `Timestamp` TIMESTAMP NOT NULL,
  `LogCause` VARCHAR(80) NOT NULL,
  `LogEntry` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`LogId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `zes_sviss`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `zes_sviss`;
INSERT INTO `zes_sviss`.`User` (`UserNr`, `Username`, `Password`, `PersName`, `EMail`, `AccountType`, `Disabled`) VALUES (NULL, 'admin', 'c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec', 'adminUser', 'test@gmx.at', 'ADMIN', false);

COMMIT;

